import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twi-Twi-Ter",
  description:
    "Generated by create next app. Twitter alternative. Twitter clone for beginners.",
  keywords: [
    "#twittertutorial",
    "#twittertips",
    "#twittermarketing",
    "#socialmediamarketing",
    "#socialmedia",
    "#tutorial",
    "#learn",
    "#growyourbusiness",
    "#increaseyourreach",
    "#connectwithyouraudience",
  ],
  openGraph: {
    siteName: "Twi-Twi-Ter",
    title: "Twi-Twi-Ter - A twitter clone",
    description:
      "Generated by create next app. Twitter alternative. Twitter clone for beginners.",
  },
  twitter: {
    creatorId: "@dickinsontiwari",
    title: "Twi-Twi-Ter",
    card: "summary",
    site: "https://twitter-tutorial.delta.vercel.app",
    description:
      "Generated by create next app. Twitter alternative. Twitter clone for beginners.",
  },
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        {" "}
        <meta
          name="google-site-verification"
          content="rxjXUQfb2q0XB-9D6w9YKSkm1m4JUHqDs6l8tgXCPuQ"
        />
        <body className={inter.className}>
          {modal}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
