import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { Metadata } from 'next'
const inter = Inter({ subsets: ['latin'] })

export const metadata:Metadata = {
  title: 'Twi-Twi-Ter',
  description: 'Generated by create next app. Twitter alternative. Twitter clone for beginners.',
  openGraph:{
    siteName:"Twi-Twi-Ter",
  },
  twitter:{
       creatorId:"@dickinsontiwari",
       title:"Twi-Twi-Ter",
       card:"summary",
       site:"https://twitter-tutorial.delta.vercel.app",

       
  }

}

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode,
  modal:React.ReactNode
  
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>{modal}{children}</body>
    </html>
    </ClerkProvider>
  )
}
